version: '3.8'

services:
  fluentbit:
    environment:
      FBIT_INPUT_PORT: 24224
      FBIT_OUTPUT_ES_HOST: ${DC_ELASTIC_HOST}
      FBIT_OUTPUT_ES_PORT: ${DC_ELASTIC_PORT}
    volumes:
      - ./config.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/custom.parsers.conf:ro
    ports:
      - 127.0.0.1:${DC_LOGS_COLLECTOR_PORT}:24224
      - 127.0.0.1:${DC_LOGS_COLLECTOR_PORT}:24224/udp
    networks:
      - es_net

networks:
  es_net:
    name: ${DC_NET_ELASTIC}
    driver: bridge
