version: '3.8'

services:
  monitor_host:
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}"
  monitor_containers:
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}"
  monitor_storage:
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml:ro
    ports:
      - 127.0.0.1:${DC_MONITOR_STORAGE_PORT}:9090
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}"
  