version: '3.8'

services:
  grafana:
    image: ${DC_GRAFANA_IMAGE}
    restart: unless-stopped
    volumes:
      - grafana_libs:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana:rw

volumes:
  grafana_libs: # @TODO: check host and containers default dashboards
    driver: local
  grafana_data:
    driver: local
