version: '3.8'

services:
  nginx:
    ports:
      - 127.0.0.1:${DC_PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}
      - 127.0.0.1:${DC_PROXY_HTTPS_PORT}:${PROXY_HTTPS_PORT}
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}"

volumes:
  proxy_templates:
    driver_opts:
      type: none
      o: bind
      device: ./templates
