version: '3.8'

services:
  nginx:
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      HOST_ELASTIC: ${DC_ELASTIC_HOST}:9200
      HOST_GRAFANA: ${DC_GRAFANA_HOST}:3000
      HOST_KIBANA: ${DC_KIBANA_HOST}:5601
      HOST_PROM: ${DC_PROM_HOST}:9090
    ports:
      - 127.0.0.1:${DC_PROXY_HTTP_PORT}:80
      - 127.0.0.1:${DC_PROXY_HTTPS_PORT}:443
    logging:
      driver: fluentd
      options:
        tag: "{{.Name}}"

volumes:
  proxy_templates:
    driver_opts:
      type: none
      o: bind
      device: ./templates
