version: '3.8'

services:
  nginx:
    image: ${DC_PROXY_IMAGE}
    environment:
      TZ: ${DC_TZ}
      HTTP_PORT: 80
      HTTPS_PORT: 443
    restart: unless-stopped
    volumes:
      - proxy_templates:/etc/nginx/templates:ro
    networks:
      - proxy_net

networks:
  proxy_net:
    name: ${DC_NET_PROXY}
    driver: bridge

volumes:
  proxy_templates:
    driver: local
