name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: bruceadams/get-release@v1.2.2
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: make release BUILD_VERSION=${CI_ACTION_REF_NAME}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./services-${{env.CI_ACTION_REF_NAME}}.zip
          asset_name: services-${{env.CI_ACTION_REF_NAME}}.zip
          asset_content_type: application/zip
